name: Publish package

on:
  release:
    types: [ created ]
  push:
    branches:
      - release-packages/**

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish package
        run: ./gradlew publish
        env:
          USERNAME_GITHUB: hieu\-dd
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}