name: Publish package

on:
  release:
    types: [ created ]
  push:
    branches:
      - release-packages/**

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Release library
        run: ./gradlew library:publish -PGITHUB_USER=${{ github.actor }} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}